'use client';
import {useEffect,useMemo,useState} from 'react';
import {Search,Star,ScanLine,MousePointer2,RefreshCw,ChevronLeft,ChevronRight,Plus,Minus,RotateCcw,Info} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Input} from '@/components/ui/input';
import {Slider} from '@/components/ui/slider';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Lang,stocks,demoCandles,stats,candleTranslation,rangeTranslation,money,volume,mean,pct,signed,validCandle} from '@/lib/market';
import type {MarketData} from '@/lib/provider';
import {Candles} from './candles';

const defaults=['NVDA','AAPL','MSFT','TSLA','AMZN','META','SPY','QQQ'];
const windows:Record<string,number>={'1M':22,'3M':63,'6M':126,'1Y':252,'2Y':504};
export default function Markets(){
 const [lang,setLang]=useState<Lang>('zh'),[symbol,setSymbol]=useState('NVDA'),[query,setQuery]=useState(''),[listTab,setListTab]=useState('watchlist');
 const [watchlist,setWatchlist]=useState<string[]>(defaults),[ready,setReady]=useState(false);
 const [data,setData]=useState<MarketData>(()=>({symbol:'NVDA',rows:demoCandles('NVDA'),source:'demo',asOf:'2025-06-30',reason:'not-configured'}));
 const [loading,setLoading]=useState(true),[retry,setRetry]=useState(0),[period,setPeriod]=useState('1Y'),[count,setCount]=useState(252),[offset,setOffset]=useState(0);
 const [active,setActive]=useState(0),[selection,setSelection]=useState<[number,number]|null>(null),[selectMode,setSelectMode]=useState(false),[readTab,setReadTab]=useState('selected');
 const zh=lang==='zh',t=(en:string,cn:string)=>zh?cn:en;
 useEffect(()=>{try{const stored=localStorage.getItem('secondorder-markets-lang');if(stored==='en'||stored==='zh')setLang(stored);const w=JSON.parse(localStorage.getItem('secondorder-markets-watchlist-v1')??'null');if(Array.isArray(w))setWatchlist([...new Set(w.filter((s:unknown)=>typeof s==='string'&&stocks.some(st=>st.symbol===s)))] as string[]);}catch{}setReady(true);},[]);
 useEffect(()=>{document.documentElement.lang=zh?'zh-CN':'en';if(!ready)return;try{localStorage.setItem('secondorder-markets-lang',lang);localStorage.setItem('secondorder-markets-watchlist-v1',JSON.stringify(watchlist));}catch{}},[lang,zh,watchlist,ready]);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setSelection(null);
 fetch(`/api/market?symbol=${symbol}`,{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<MarketData>;}).then(d=>{if(d.symbol!==symbol||!Array.isArray(d.rows)||d.rows.length<26||!d.rows.every(validCandle))throw new Error();setData(d);setLoading(false);setOffset(0);}).catch(()=>{if(abort.signal.aborted)return;const rows=demoCandles(symbol);setData({symbol,rows,source:'demo',asOf:rows.at(-1)!.date,reason:'unavailable'});setLoading(false);setOffset(0);});return()=>abort.abort();
 },[symbol,retry]);
 const viewCount=Math.min(count,data.rows.length),maxOffset=Math.max(0,data.rows.length-viewCount),safeOffset=Math.min(offset,maxOffset);
 const rows=useMemo(()=>data.rows.slice(Math.max(0,data.rows.length-safeOffset-viewCount),data.rows.length-safeOffset),[data,safeOffset,viewCount]);
 useEffect(()=>{setActive(rows.length-1);setSelection(null);},[rows]);
 const index=Math.min(active,rows.length-1),c=rows[index],s=stats(data.rows),latest=s.c,prev=data.rows.at(-2)!;
 const stock=stocks.find(st=>st.symbol===data.symbol)!,sample=data.source==='demo';
 const safeSelection=selection&&Math.max(...selection)<rows.length?selection:null;
 const picked=safeSelection?rows.slice(Math.min(...safeSelection),Math.max(...safeSelection)+1):null;
 const filtered=stocks.filter(st=>(listTab==='all'||watchlist.includes(st.symbol))&&`${st.symbol} ${st.name} ${st.zh}`.toLowerCase().includes(query.toLowerCase()));
 const toggle=(ticker:string)=>setWatchlist(current=>current.includes(ticker)?current.filter(s=>s!==ticker):[...current,ticker]);
 const setWindow=(p:string)=>{setPeriod(p);setCount(windows[p]);setOffset(0);setSelection(null);};
 const zoom=(factor:number)=>{setCount(n=>Math.max(15,Math.min(data.rows.length,Math.round(n*factor))));setPeriod('');setSelection(null);};
 const old=data.rows.at(-6)!,week=data.rows.slice(-5),oldWeek=data.rows.slice(-10,-5),wv=mean(week.map(r=>r.volume)),ov=mean(oldWeek.map(r=>r.volume));
 const wr=mean(week.map(r=>pct(r.high,r.low))),or=mean(oldWeek.map(r=>pct(r.high,r.low)));
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const controller=new AbortController();
 const tool={name:'read_candle_translation',description:'Read the plain-language explanation of a completed daily candle for the selected stock.',inputSchema:{type:'object',properties:{date:{type:'string'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const date=(input as {date?:string})?.date,candle=data.rows.find(r=>r.date===date);if(!candle)throw new Error('Date outside available history');return {symbol:data.symbol,date,source:data.source,translation:candleTranslation(candle,lang)};}};
 void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[data,lang]);
 return <main className="terminal">
  <header className="topbar"><a className="brand" href="/"><span className="mark">Ⅱ</span><span>SecondOrder Markets</span></a><span className="tagline">{t('Markets, translated.','把行情讲明白')}</span><span className="edition">v0.1</span><div className="lang" aria-label={t('Language','语言')}><button aria-pressed={!zh} className={!zh?'active':''} onClick={()=>setLang('en')}>EN</button><button aria-pressed={zh} className={zh?'active':''} onClick={()=>setLang('zh')}>中文</button></div></header>
  <div className="terminal-body">
   <aside className="stock-sidebar"><Tabs value={listTab} onValueChange={setListTab}><TabsList variant="line"><TabsTrigger value="watchlist">{t('Watchlist','自选股')} <small>{watchlist.length}</small></TabsTrigger><TabsTrigger value="all">{t('All stocks','全部股票')}</TabsTrigger></TabsList><TabsContent value={listTab} className="stock-tab-content">
    <div className="sidebar-search"><Search size={15}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Ticker / company','代码 / 公司名称')} aria-label={t('Search stocks','搜索股票')}/></div>
    <div className="list-caption"><span>{query?t(`${filtered.length} results`,`${filtered.length} 个结果`):listTab==='all'?t('100 stocks + 2 ETFs','100 支股票 + 2 只 ETF'):t('Saved in this browser','已保存到此浏览器')}</span><span>{t('☆ Add to watchlist','☆ 加入自选')}</span></div>
    <div className="stock-list">{filtered.length?filtered.map(st=><div className={`stock-row ${symbol===st.symbol?'selected':''}`} key={st.symbol}><button className="stock-pick" onClick={()=>{setSymbol(st.symbol);}} aria-pressed={symbol===st.symbol}><strong>{st.symbol}<small>{st.kind==='ETF'?'ETF':''}</small></strong><span>{zh?st.zh:st.name}</span></button><button className={`star ${watchlist.includes(st.symbol)?'saved':''}`} onClick={()=>toggle(st.symbol)} aria-pressed={watchlist.includes(st.symbol)} aria-label={watchlist.includes(st.symbol)?t(`Remove ${st.symbol} from watchlist`,`从自选股移除 ${st.symbol}`):t(`Add ${st.symbol} to watchlist`,`添加 ${st.symbol} 到自选股`)}><Star size={15}/></button></div>):<div className="list-empty"><p>{query?t('No matching stocks.','没有匹配的股票。'):t('Your watchlist is empty.','自选股暂时为空。')}</p>{!query&&<button onClick={()=>setListTab('all')}>{t('Browse all stocks','查看全部股票')}</button>}</div>}</div>
    </TabsContent></Tabs><div className="sidebar-foot">{t('US stocks & ETFs','美股与 ETF')}</div>
   </aside>
   <section className="chart-workspace" aria-busy={loading}>
    <div className="instrument-bar"><div className="instrument-name"><h1>{data.symbol}</h1><span>{zh?stock.zh:stock.name}</span><span className="instrument-kind">{stock.kind==='ETF'?'ETF':t('US','美股')}</span><button className={`star ${watchlist.includes(data.symbol)?'saved':''}`} onClick={()=>toggle(data.symbol)} aria-pressed={watchlist.includes(data.symbol)} aria-label={t('Toggle watchlist membership','添加或移除自选股')}><Star size={16}/></button></div><div className="instrument-price"><strong>{money(latest.close)}</strong><span className={s.change>=0?'up':'down'}>{signed(s.change)}</span></div></div>
    <div className="chart-toolbar"><span className="interval">{t('1D','日 K')}</span><RadioGroup value={period} onValueChange={setWindow} className="period-group" aria-label={t('Chart range','图表范围')}>{Object.keys(windows).map(p=><label className={period===p?'active':''} key={p}><RadioGroupItem value={p}/>{zh?({'1M':'1月','3M':'3月','6M':'6月','1Y':'1年','2Y':'2年'} as Record<string,string>)[p]:p}</label>)}</RadioGroup><span className="toolbar-divider"/><button className={selectMode?'active':''} onClick={()=>{setSelectMode(v=>!v);setSelection(null);}} aria-pressed={selectMode}><ScanLine size={15}/>{t('Range','选一段')}</button><div className="zoom-buttons"><button onClick={()=>zoom(.75)} disabled={viewCount<=15} aria-label={t('Zoom in','放大图表')}><Plus size={16}/></button><button onClick={()=>zoom(1.35)} disabled={viewCount>=data.rows.length} aria-label={t('Zoom out','缩小图表')}><Minus size={16}/></button><button onClick={()=>setWindow('1Y')} aria-label={t('Reset chart','重置图表')}><RotateCcw size={14}/></button></div></div>
    <div className="ohlc"><b>{c.date}</b>{[[t('O','开'),c.open],[t('H','高'),c.high],[t('L','低'),c.low],[t('C','收'),c.close]].map(([key,value])=><span key={key}><small>{key}</small>{Number(value).toFixed(2)}</span>)}<span><small>{t('Vol','量')}</small>{volume(c.volume)}</span></div>
    <div className="chart-canvas"><Candles rows={rows} active={index} onActive={setActive} selection={safeSelection} onSelection={setSelection} selectMode={selectMode} lang={lang}/></div>
    <div className="chart-navigation"><button onClick={()=>{setOffset(n=>Math.min(maxOffset,n+Math.max(1,Math.round(viewCount/4))));}} disabled={safeOffset>=maxOffset} aria-label={t('Earlier candles','查看更早的 K 线')}><ChevronLeft size={17}/></button><Slider min={0} max={Math.max(1,maxOffset)} step={1} value={[maxOffset-safeOffset]} onValueChange={([n])=>setOffset(maxOffset-n)} disabled={!maxOffset} aria-label={t('Browse price history','浏览历史行情')}/><button onClick={()=>setOffset(n=>Math.max(0,n-Math.max(1,Math.round(viewCount/4))))} disabled={!safeOffset} aria-label={t('Later candles','查看更晚的 K 线')}><ChevronRight size={17}/></button><button className="latest-button" onClick={()=>setOffset(0)} disabled={!safeOffset}>{t('Latest','最近')}</button></div>
    <div className="chart-caption"><span>{rows[0].date} ~ {rows.at(-1)!.date} · {t(`${rows.length} candles`,`${rows.length} 根 K 线`)}</span><div className="legend"><span><i className="blue"/>{t('Close ≥ open','收 ≥ 开')}</span><span><i className="copper"/>{t('Close < open','收 < 开')}</span></div></div>
    <div className={`data-status ${sample?'sample':''}`} role="status"><Info size={14}/><span>{sample?t('Demo data · Not actual prices · 2025-06-30','演示数据 · 非真实行情 · 2025-06-30'):t(`Twelve Data · Completed sessions · ${data.asOf}`,`Twelve Data · 已完成日 K · ${data.asOf}`)}{loading?t(' · Loading…',' · 加载中…'):data.reason==='unavailable'?t(' · Data connection unavailable',' · 暂时无法连接数据源'):''}</span><button disabled={loading} onClick={()=>setRetry(n=>n+1)} aria-label={t('Refresh history','刷新历史数据')}><RefreshCw size={14}/></button></div>
   </section>
   <aside className="reader"><div className="reader-title"><span className="section-index">02</span><h2>{t('Chart explained','行情解读')}</h2><span className="reader-mark">Aa</span></div>
    <Tabs value={readTab} onValueChange={setReadTab}><TabsList variant="line"><TabsTrigger value="selected">{t('Candle','看这根')}</TabsTrigger><TabsTrigger value="latest">{t('Latest','看当天')}</TabsTrigger><TabsTrigger value="changed">{t('Changes','看变化')}</TabsTrigger></TabsList>
     <TabsContent value="selected"><div className="reader-meta">{picked?t(`${picked.length} SELECTED SESSIONS`,`${picked.length} 个交易日的区间`):t('CANDLE EXPLANATION','这根 K 线')}</div><div className="reader-date">{picked?`${picked[0].date} ~ ${picked.at(-1)!.date}`:c.date}</div><p className="reading" aria-live="polite">{picked?rangeTranslation(picked,lang):candleTranslation(c,lang)}</p><div className="evidence"><h3>{t('What the chart shows','对应数据')}</h3>{(picked?[[t('Close-to-close change','期间涨跌'),signed(pct(picked.at(-1)!.close,picked[0].close))],[t('Sessions','交易日'),String(picked.length)]]:[[t('Open → close','开盘 → 收盘'),signed(pct(c.close,c.open))],[t('High / low','最高 / 最低'),`${money(c.high)} / ${money(c.low)}`],[t('Shares traded','成交量'),volume(c.volume)]]).map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div>{picked&&<button className="text-button" onClick={()=>setSelection(null)}>{t('Clear selection','取消选择')}</button>}<div className="reader-help"><MousePointer2 size={16}/><p>{selectMode?t('Drag across the chart to read a stretch of price history.','在图上拖动，看看这一段发生了什么。'):t('Hover or tap a candle to read it.','把鼠标移到 K 线上，或轻触一根，就能看到解读。')}</p></div></TabsContent>
     <TabsContent value="latest"><div className="reader-meta">{t('LAST COMPLETED SESSION','最近一个交易日')} · {data.asOf}</div><p className="reading">{candleTranslation(latest,lang)}</p><div className="context-block"><h3>{t('Price','价格')}</h3><b className={s.change>=0?'up':'down'}>{signed(s.change)}</b><p>{t(`The close changed from ${money(prev.close)} to ${money(latest.close)}.`,`收盘价从 ${money(prev.close)} 变为 ${money(latest.close)}。`)}</p></div><div className="context-block"><h3>{t('Volume','成交量')}</h3><b>{s.ratio.toFixed(2)}×</b><p>{t('Compared with the average daily volume over the previous 20 sessions.','是此前 20 个交易日日均成交量的倍数。')}</p></div><div className="context-block"><h3>{t('20-session price range','前 20 日价格区间')}</h3><b>{money(s.low)} ~ {money(s.high)}</b><p>{latest.close>s.high?t('The close is above the previous range.','收盘价超过了此前 20 天的最高价。'):latest.close<s.low?t('The close is below the previous range.','收盘价低于此前 20 天的最低价。'):t('The close remains inside the previous range.','收盘价还在此前 20 天的价格范围内。')}</p></div></TabsContent>
     <TabsContent value="changed"><div className="reader-meta">{t('PAST FIVE SESSIONS','过去五个交易日')}</div><div className="reader-date">{old.date} ~ {latest.date}</div><p className="reading">{rangeTranslation(data.rows.slice(-6),lang)}</p><div className="evidence"><h3>{t('Previous five sessions → latest five','前五个交易日 → 最近五个交易日')}</h3>{[[t('Closing price','收盘价'),money(old.close),money(latest.close)],[t('Average volume','平均成交量'),volume(ov),volume(wv)],[t('Average daily range','平均日内波幅'),`${or.toFixed(2)}%`,`${wr.toFixed(2)}%`]].map(([label,a,b])=><div className="change-evidence" key={label}><span>{label}</span><b>{a} → {b}</b></div>)}</div></TabsContent>
    </Tabs>
    <details className="method"><summary>{t('How we read the chart','怎么看出来的？')}</summary><p>{t('We compare the open and close, the length of the wicks, and how volume differs from its recent average. Daily candles don’t show the order in which the high and low occurred.','我们对比开盘和收盘、上下影线的长度，以及成交量与近期平均水平的差别。日 K 看不出最高价和最低价谁先出现。')}</p></details>
   </aside>
  </div>
  <footer><span>SecondOrder Markets</span><span>{t('Markets, translated.','把行情讲明白')}</span><span>v0.1</span></footer>
 </main>;
}
